VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04
  config.vm.box = "bento/ubuntu-16.04"

  #below box has an issue, https://bugs.launchpad.net/cloud-images/+bug/1569237
  #config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"

  config.vm.hostname = "devstack"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.provision :shell, :path => "provision.sh"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

end
